"""
Train machine learning models on the basic data subset (Dataset generated by JSBACH3.2 analog to an observational flux dataset) using a GPU.
"""

#%%
import os
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim

from ml_models import Resnet_model18
from model_train_function import trainings_loop, SimpleDataset

#%%

if __name__ == "__main__":

    ## train on datasets with different sizes
    # num_addyr = 20
    # size_name = f"obs_{num_addyr}yr"

    # set parameter
    acronym = f"resnet18_basic_1"
    n_epochs = 300
    lr = np.pi * 10 ** (-4)  # Learning rate
    device = "cuda"  # "cuda"
    batch_size = 4
    num_input = 11
    num_output = 365 * 2

    # set gpu
    device = torch.device(device)

    ## load trainings and validation data
    data_path = "data/jsbach_space_time_splits/datasets/basic_obs"
    
    # train first basic set and then build loops over each sample
    train_meteo = np.load(f"{data_path}/basic_train_feat.npy")
    train_static = np.load(f"{data_path}/basic_train_stat.npy")
    train_targets = np.load(f"{data_path}/basic_train_tar.npy")

    val_meteo = np.load(f"{data_path}/basic_val_feat.npy")
    val_static = np.load(f"{data_path}/basic_val_stat.npy")
    val_targets = np.load(f"{data_path}/basic_val_tar.npy")

    # for each model five different initialisations
    for j in range(5):

        seed = 42 + j  # Generate unique seeds
        torch.manual_seed(seed)
        torch.cuda.manual_seed(seed)

        train_dataset = SimpleDataset(
            train_meteo, train_static, train_targets, device=device
        )
        train_dataloader = torch.utils.data.DataLoader(
            train_dataset,
            batch_size=batch_size,
            shuffle=True,
            worker_init_fn=lambda _: torch.manual_seed(seed),
        )

        val_dataset = SimpleDataset(
            val_meteo, val_static, val_targets, device=device
        )
        val_dataloader = torch.utils.data.DataLoader(
            val_dataset,
            batch_size=batch_size,
            shuffle=True,
            worker_init_fn=lambda _: torch.manual_seed(seed),
        )

        # init model
        model = Resnet_model18(num_input, num_output).to(device)

        optimizer = optim.AdamW(
            model.parameters(), lr=lr, weight_decay=0.1
        )  # Optimizer
        loss_fn = nn.MSELoss()  # Loss function
        scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(
            optimizer, T_0=75
        )  # Learning rate scheduler

        # path
        path = f"trained_models/version1/{acronym}_{n_epochs}/init_{j}"
        os.makedirs(path, exist_ok=True)

        # train function
        print(path)
        loss_data = trainings_loop(
            optimizer=optimizer,
            model=model,
            loss_fn=loss_fn,
            scheduler=scheduler,
            train_loader=train_dataloader,
            val_loader=val_dataloader,
            n_epochs=n_epochs,
            date=acronym,
            batch_size=batch_size,
            path=path,
        )

        np.savetxt(f"{path}/m{acronym}_E_{n_epochs}.csv", loss_data, delimiter=";")
